import React from 'react';
import { mockApplications, mockRiskExplanations } from '../../utils/mockData';
import { formatCurrency, formatPercent } from '../../utils/formatters';
import RiskGauge from '../../components/charts/RiskGauge';
import { TrendingUp, TrendingDown, AlertTriangle, CheckCircle } from 'lucide-react';

export default function RiskReport() {
  const app = mockApplications[0]; // Latest application
  const explanations = mockRiskExplanations;

  return (
    <div className="slide-up">
      <div className="page-header">
        <h1>Risk Assessment Report</h1>
        <p>Application {app.id} — Detailed AI-powered risk analysis with explanations.</p>
      </div>

      <div className="grid grid-3 gap-6" style={{ marginBottom: 32 }}>
        {/* Risk Gauge */}
        <div className="card card-highlight" style={{ gridColumn: 'span 1' }}>
          <h4 style={{ marginBottom: 8 }}>Overall Risk Score</h4>
          <RiskGauge score={app.riskScore} size={200} />
          <div style={{ textAlign: 'center', fontSize: '0.8125rem', color: 'var(--color-ivory-muted)' }}>
            Score Range: 0 (High Risk) — 850 (Low Risk)
          </div>
        </div>

        {/* Key Metrics */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16, gridColumn: 'span 2' }}>
          <div className="grid grid-3 gap-4">
            <div className="stat-card">
              <div className="stat-label">Debt-to-Income Ratio</div>
              <div className="stat-value" style={{ color: app.dti < 0.36 ? 'var(--color-emerald)' : 'var(--color-ruby)' }}>{formatPercent(app.dti)}</div>
              <div className="stat-change positive">{app.dti < 0.36 ? <><CheckCircle size={12} /> Below 36% threshold</> : <><AlertTriangle size={12} /> Above 36% threshold</>}</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Loan-to-Income Ratio</div>
              <div className="stat-value" style={{ color: app.lti < 4 ? 'var(--color-emerald)' : 'var(--color-amber)' }}>{app.lti}x</div>
              <div className="stat-change positive">{app.lti < 4 ? <><CheckCircle size={12} /> Manageable level</> : <><AlertTriangle size={12} /> Elevated</>}</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Credit Score</div>
              <div className="stat-value">{app.creditScore}</div>
              <div className="stat-change positive"><TrendingUp size={12} /> Good standing</div>
            </div>
          </div>

          <div className="card">
            <h4 style={{ marginBottom: 12 }}>Application Summary</h4>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px 32px' }}>
              <div><span className="label-caps">Loan Amount</span><div style={{ fontWeight: 600, color: 'var(--color-gold)', fontFamily: 'var(--font-display)', fontSize: '1.25rem', marginTop: 2 }}>{formatCurrency(app.loanAmount)}</div></div>
              <div><span className="label-caps">Purpose</span><div style={{ fontWeight: 500, marginTop: 2 }}>{app.purpose}</div></div>
              <div><span className="label-caps">Employment</span><div style={{ fontWeight: 500, marginTop: 2 }}>{app.employment}</div></div>
              <div><span className="label-caps">Annual Income</span><div style={{ fontWeight: 500, marginTop: 2 }}>{formatCurrency(app.income)}</div></div>
            </div>
          </div>
        </div>
      </div>

      {/* Explanation Section */}
      <div className="card" style={{ marginBottom: 24 }}>
        <div className="card-header">
          <h3>AI Model Explanations</h3>
          <span className="badge badge-gold">SHAP Analysis</span>
        </div>
        <p style={{ color: 'var(--color-ivory-muted)', fontSize: '0.875rem', marginBottom: 20 }}>
          These explanations are generated by our AI model using SHAP (SHapley Additive exPlanations) values, translated into plain language for transparency.
        </p>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {explanations.map((exp, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 12, padding: '12px 16px', background: exp.impact === 'positive' ? 'rgba(46,204,113,0.06)' : 'rgba(231,76,60,0.06)', border: `1px solid ${exp.impact === 'positive' ? 'rgba(46,204,113,0.2)' : 'rgba(231,76,60,0.2)'}`, borderRadius: 'var(--radius-md)' }}>
              <div style={{ marginTop: 2 }}>
                {exp.impact === 'positive' ? <TrendingUp size={18} color="#2ECC71" /> : <TrendingDown size={18} color="#E74C3C" />}
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: 600, fontSize: '0.9375rem', marginBottom: 2 }}>{exp.factor}</div>
                <div style={{ fontSize: '0.8125rem', color: 'var(--color-ivory-muted)' }}>{exp.explanation}</div>
              </div>
              <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1rem', color: exp.impact === 'positive' ? 'var(--color-emerald)' : 'var(--color-ruby)' }}>
                {exp.weight > 0 ? '+' : ''}{(exp.weight * 100).toFixed(0)}%
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
