// ===========================
// PDF Report Generator (using PDFKit)
// ===========================
const PDFDocument = require('pdfkit');

/**
 * Generate a risk assessment PDF report
 * @param {object} application - The loan application
 * @param {object} riskScore - The risk score data
 * @returns {PDFDocument} - Piped PDF stream
 */
const generateRiskReportPDF = (application, riskScore) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  // ---- Header ----
  doc.fontSize(22).font('Helvetica-Bold').fillColor('#3D1E6D')
    .text('Loan Risk Assessment Report', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('#888')
    .text('Intelligent Loan Risk Assessment System', { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#D4AF37').lineWidth(1).stroke();
  doc.moveDown(1);

  // ---- Application Details ----
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#1A1240')
    .text('Application Details');
  doc.moveDown(0.5);
  doc.fontSize(10).font('Helvetica').fillColor('#333');

  const appDetails = [
    ['Application ID', application._id?.toString() || 'N/A'],
    ['Applicant', application.applicantId?.name || 'N/A'],
    ['Loan Amount', `$${(application.financialInfo?.loanAmountRequested || 0).toLocaleString()}`],
    ['Annual Income', `$${(application.financialInfo?.income || 0).toLocaleString()}`],
    ['Employment', application.personalInfo?.employmentType || 'N/A'],
    ['Tenure', `${application.financialInfo?.tenure || 'N/A'} months`],
    ['Status', application.status?.toUpperCase() || 'N/A'],
    ['Submitted', application.createdAt ? new Date(application.createdAt).toLocaleDateString() : 'N/A'],
  ];

  appDetails.forEach(([label, value]) => {
    doc.font('Helvetica-Bold').text(`${label}: `, { continued: true })
      .font('Helvetica').text(value);
  });

  doc.moveDown(1);

  // ---- Risk Assessment ----
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#1A1240')
    .text('Risk Assessment');
  doc.moveDown(0.5);
  doc.fontSize(10).font('Helvetica').fillColor('#333');

  if (riskScore) {
    const scoreColor = riskScore.riskLevel === 'low' ? '#2ECC71'
      : riskScore.riskLevel === 'medium' ? '#F39C12' : '#E74C3C';

    doc.font('Helvetica-Bold').text('Risk Score: ', { continued: true })
      .fillColor(scoreColor).text(`${riskScore.riskScore}/100 (${riskScore.riskLevel?.toUpperCase()})`);
    doc.fillColor('#333');
    doc.font('Helvetica-Bold').text(`Confidence: `, { continued: true })
      .font('Helvetica').text(`${((riskScore.confidenceScore || 0) * 100).toFixed(1)}%`);
    doc.moveDown(0.5);

    if (riskScore.fraudFlag) {
      doc.fillColor('#E74C3C').font('Helvetica-Bold')
        .text(`⚠ FRAUD FLAG: ${riskScore.fraudReason || 'Suspicious patterns detected'}`);
      doc.fillColor('#333');
      doc.moveDown(0.5);
    }

    // Top Factors
    if (riskScore.topFactors?.length > 0) {
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#1A1240')
        .text('Key Risk Factors');
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica').fillColor('#333');
      riskScore.topFactors.forEach((factor, i) => {
        const impactSymbol = factor.impact === 'positive' ? '▲' : '▼';
        const impactColor = factor.impact === 'positive' ? '#2ECC71' : '#E74C3C';
        doc.fillColor(impactColor).text(`  ${impactSymbol} `, { continued: true })
          .fillColor('#333').font('Helvetica-Bold').text(`${factor.feature}: `, { continued: true })
          .font('Helvetica').text(factor.description);
      });
      doc.moveDown(0.5);
    }

    // Plain Language Explanation
    if (riskScore.plainLanguageExplanation?.length > 0) {
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#1A1240')
        .text('Explanation');
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica').fillColor('#555');
      riskScore.plainLanguageExplanation.forEach(line => {
        doc.text(`• ${line}`);
      });
    }
  } else {
    doc.text('Risk assessment has not been completed yet.');
  }

  // ---- Footer ----
  doc.moveDown(2);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#D4AF37').lineWidth(0.5).stroke();
  doc.moveDown(0.5);
  doc.fontSize(8).font('Helvetica').fillColor('#aaa')
    .text(`Generated on ${new Date().toLocaleString()} | Intelligent Loan Risk Assessment System`, { align: 'center' });
  doc.text('This report is auto-generated by AI. Final decisions are made by authorized loan officers.', { align: 'center' });

  return doc;
};

module.exports = { generateRiskReportPDF };
